version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    groups:
      github-actions:
        patterns:
          - '*'
    labels:
      - 'commit::chore'
      - 'type::automated-pr'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      production_dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      development_dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    labels:
      - 'commit::chore'
      - 'type::automated-pr'
