# Problem

# In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

# The reverse complement of a DNA string s
# is the string sc formed by reversing the symbols of s

# , then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

# Given: A DNA string s

# of length at most 1000 bp.

# Return: The reverse complement sc
# of s

# .
# Sample Dataset

# AAAACCCGGT

# Sample Output

# ACCGGGTTTT
def reverse(s):
    str = ""
    for i in s:
        str = i + str
    return str

DNA="TGGCTACGTTAGTTTCCTGTCCCAGGTTTGCGTGCGAATGTGGGCTTAGGAGGCTGTCATTCATTCCGGGGTCAGGTTTATTTAATGGGCAAGTGACAACTTCCTTCCAGAGTTACGATTGAACATTTCTCTCTAACTATTGGTCAACGCTCCACATCAGACTCATGAAGGAGGTAAGCTCGTCTAATAAGCATGCCCACTTAAATCCTTGGTTTCTCCTACGCCTCGTAGACCAGCTGGGACAAAGGCCGCTTGAGTTAAGTTAGGCATTGTTCCTCGCCCGTTGTGCAGGATGACGTAGGACTGTGGTATTGCCCTTCCCCCAAACGTTGACGAAGTAAGCGACTTGACTATCGGTGATCTCGTCGCGACTGGAAAATGCTCTCACGGTTCGTTTCACTGTCTAGCACCAATAGAACAGCCATGCTGGCTTTCCGCAAATTTTCAGGGCACGAAGAATCCGAGGAAGGAAATCAGTCGGTCAAGTTAACCGGTTAAGATATGTGTATGACGAGATTTTGTAGCACTTAGACTGGATATCTTTCAGTAACAAGTTCAATAGCGCTAGTAGCGAGAGCCAATAGGCTGGGGTAAGCTAACTTGAATCGTGGCGGGAGGTCGACCGAGGTACTTGGGAGGGTATGGAAAGATAAGTATATGGGCTAGCTCCTAATGGCGAATGATCCGTTCCTAGCTATCAACGCAATTACCAACCCTTAACGGCACGCTATATAGCATGGGGACTGGGTGCCAACATGCGCGGTAAGAAATGCATGGAGAGTGGCAGGGCGTCCTCTAACGAATGAGCAGTGCGAGGCCTCACCGTGACTGACCATTCGGGAGGGAGTTACCGTCCACGTATCTGCCCCGGAGAAGTGCTCGGGAGCCCAAGGATCGTATGGAGGTGACACCGTATGAGATTT"

CDNA=""

for i in range (0,len(DNA)):
    if(DNA[i]=='A'):
        CDNA+='T'
    elif(DNA[i]=='T'):
        CDNA+='A'
    elif(DNA[i]=='C'):
        CDNA+='G'
    elif(DNA[i]=='G'):
        CDNA+='C'

print(reverse(CDNA))


