name: Publish package to NPM

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Choose release type
        options:
          - patch
          - minor
        default: patch
      beta:
        type: boolean
        description: Prerelease
        default: false

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          ref: v0.x
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Bump version with NPM version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: bump-version
        run: |
          TYPE=${{ github.event.inputs.type }}
          BETA=${{ github.event.inputs.beta }}
          if [ "$BETA" = "true" ]; then
            npm version $TYPE --preid=beta --no-git-tag-version
          else
            npm version $TYPE --no-git-tag-version
          fi
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "newTag=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Version bumped to: $NEW_VERSION"
      - name: Build project
        run: npm run build
      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit and push changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: bump version to ${{ steps.bump-version.outputs.newTag }}" -n
            git push origin v0.x --no-verify
          fi
